#!/usr/bin/env bash
# Render docs/fork/PATCHES.md from the commit stack and PATCHES.yaml annotations.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
BASE=$(git describe --tags --abbrev=0 --match 'v[0-9]*')
OUT=docs/fork/PATCHES.md
YAML=docs/fork/PATCHES.yaml

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
git log --reverse --no-merges --format='%h%x09%s' "$BASE"..HEAD > "$TMP/commits"
cut -f2- "$TMP/commits" > "$TMP/subjects"

# One python pass for the whole stack: the YAML is loaded once and every
# subject is annotated in order, emitting "layer<TAB>pr<TAB>drop" per line.
# Empty fields are written as "-" so that the reader below cannot collapse
# adjacent tabs.
python3 - "$YAML" "$TMP/subjects" > "$TMP/annotations" <<'PY'
import sys, yaml

entries = yaml.safe_load(open(sys.argv[1])) or []
exact, prefixes = {}, []
for e in entries:
    subs = e.get('subjects') or ([e['subject']] if e.get('subject') else [])
    for s in subs:
        if s in exact:
            sys.exit(f"PATCHES.yaml: duplicate subject {s!r}")
        exact[s] = e
    for p in e.get('prefixes') or []:
        prefixes.append((p, e))

out = []
with open(sys.argv[2]) as fh:
    for line in fh:
        subject = line.rstrip('\n')
        # An exact subject match always wins over a prefix match.
        entry = exact.get(subject)
        if entry is None:
            for p, e in prefixes:
                if subject.startswith(p):
                    entry = e
                    break
        if entry is None:
            out.append("?\t-\t(unannotated)")
            continue
        pr = entry.get('upstream_pr')
        out.append("%s\t%s\t%s" % (
            entry.get('layer') or '?',
            '-' if pr is None else pr,
            entry.get('drop') or '-',
        ))
sys.stdout.write("\n".join(out) + "\n")
PY

{
  echo "# Carried patches"
  echo
  echo "Base upstream tag: \`$BASE\`. Generated by \`make patches\` on $(date -u +%Y-%m-%d). Annotations live in PATCHES.yaml."
  echo
  echo "| Commit | Layer | Subject | Upstream PR | Drop when |"
  echo "|---|---|---|---|---|"
  paste "$TMP/commits" "$TMP/annotations" |
    while IFS=$'\t' read -r hash subject layer prnum drop; do
      # Fall back to the subject's own conventional-commit prefix when the
      # matched entry carries no layer.
      if [ "$layer" = "?" ]; then
        layer=$(printf '%s' "$subject" | sed -E 's/^(lock|feat|fix|pick)[:(].*/\1/; t; s/.*/?/')
      fi
      link=""
      [ "$prnum" != "-" ] && link="[#$prnum](https://github.com/router-for-me/CLIProxyAPI/pull/$prnum)"
      echo "| $hash | $layer | ${subject//|/\\|} | $link | $drop |"
    done
} > "$OUT"
echo "wrote $OUT"
echo "rows: $(($(grep -c '^| ' "$OUT") - 1))"
echo "unannotated rows: $(grep -c '(unannotated)' "$OUT" || true)"
